name: Norminette

on:
  push:
    branches:
      - main

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: alexandregv/norminette-action@v3
        with:
          flags: '.'
