name: Norminette

on:
  push:
    branches:
      - main

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Norminette
        uses: 42school/norminette@v3.3.58
        with:
          args: '-R CheckForbiddenSourceHeader'
